services:
  spring:
    image: maven:3.8.6-openjdk-8
    container_name: spring-container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/customer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
    networks:
      - spring-network
  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - spring-network
networks:
    spring-network:
