services:
  spring:
    image: maven:3.8.6-openjdk-8
    container_name: backend
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
    networks:
      - net
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root 
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - net
networks:
    net:
